from sqlalchemy import Column, BigInteger, String, Boolean, Text, DateTime
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from database.base import Base

class Chat(Base):
    __tablename__ = "chats"

    # Primary Key utilizing Snowflake IDs (generated by the FastAPI server)
    id = Column(BigInteger, primary_key=True, index=True)

    # False represents a 1-on-1 private chat, True represents a group chat
    # Extremely memory efficient (1 byte in PostgreSQL)
    is_group = Column(Boolean, nullable=False, default=False)

    # The following fields are primarily used for group chats. 
    # For private chats, these will typically be NULL.
    title = Column(String(100), nullable=True)
    
    # A short description or rules for the group
    about_text = Column(String(255), nullable=True)
    
    # URL pointing to the group's avatar stored in AWS S3 / MinIO
    profile_pic_url = Column(Text, nullable=True)

    # Audit timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # SQLAlchemy ORM relationship for easy joins with participants
    # Assuming Participant model will be created next
    participants = relationship("Participant", back_populates="chat", cascade="all, delete-orphan")