from sqlalchemy import Column, BigInteger, String, Boolean, Text, DateTime
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from database.base import Base

# Only the first line of the last message is ever rendered in a chat list,
# so only that much is worth denormalizing onto this (small, hot) table -
# a message itself can be up to config.MAX_MESSAGE_CONTENT_LENGTH.
LAST_MESSAGE_PREVIEW_LENGTH = 120

class Chat(Base):
    __tablename__ = "chats"

    # Primary Key utilizing Snowflake IDs (generated by the FastAPI server)
    id = Column(BigInteger, primary_key=True, index=True)

    # False represents a 1-on-1 private chat, True represents a group chat
    # Extremely memory efficient (1 byte in PostgreSQL)
    is_group = Column(Boolean, nullable=False, default=False)

    # The following fields are primarily used for group chats. 
    # For private chats, these will typically be NULL.
    title = Column(String(100), nullable=True)
    
    # A short description or rules for the group
    about_text = Column(String(255), nullable=True)
    
    # URL pointing to the group's avatar stored in AWS S3 / MinIO
    profile_pic_url = Column(Text, nullable=True)

    # Audit timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Denormalized recency, bumped by crud_message.create_message on every
    # new message. Lets the chat list (home screen) be sorted/paginated by
    # "last activity" via a small join against Participant, instead of an
    # aggregate MAX(messages.id) per chat over a multi-billion row table.
    #
    # Defaults to created_at (same server-side NOW(), so they match exactly)
    # instead of NULL: a chat with no messages yet should rank by when it was
    # created, mixed in with messaged chats in the same timeline - not get
    # shoved to the end of the list as a NULL special case.
    last_message_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    last_message_id = Column(BigInteger, nullable=True)

    # The snippet the chat list shows under each chat's name. Denormalized
    # here, next to the id it belongs to, so rendering that screen stays a
    # single query: resolving last_message_id against `messages` instead
    # would be one lookup per listed chat into a RANGE-partitioned table
    # with no partition to prune to (the id is known, created_at isn't),
    # i.e. every partition probed, per chat, on the most-loaded screen.
    # NULL means "nothing to preview" - a chat with no messages, or one
    # whose last message was deleted or has no text.
    last_message_preview = Column(String(LAST_MESSAGE_PREVIEW_LENGTH), nullable=True)

    # Chat-wide receipt watermarks: the highest message id that literally
    # every *current* participant has delivered/read, i.e.
    # MIN(Participant.last_delivered_message_id) / MIN(last_read_message_id)
    # across this chat's participants (see crud_participant's
    # recompute_chat_receipt_cursors). Denormalized here for the same reason
    # as last_message_id above: a message's single/double-grey/double-blue
    # check status (database.models.message.MessageStatus) is never stored
    # on the message - a group can have up to ~1000 recipients, so a literal
    # per-message status column would mean up to ~1000x the writes on a
    # table already sized for tens of billions of rows. Comparing a
    # message's id against these two columns instead is one O(1) integer
    # comparison, independent of group size or message history length.
    # NULL means "no participant has acknowledged anything yet".
    all_delivered_up_to_message_id = Column(BigInteger, nullable=True)
    all_read_up_to_message_id = Column(BigInteger, nullable=True)

    # Same rollup, one step further: MIN(Participant.last_played_message_id)
    # across current participants - the highest message id every participant
    # has actually listened to. Only ever compared against voice-recording
    # messages (see MessageStatus.PLAYED); for any other message type it's
    # irrelevant. NULL/0 means "nobody has played anything yet".
    all_played_up_to_message_id = Column(BigInteger, nullable=True)

    # SQLAlchemy ORM relationship for easy joins with participants
    # Assuming Participant model will be created next
    participants = relationship("Participant", back_populates="chat", cascade="all, delete-orphan")