# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: snowflake.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'snowflake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsnowflake.proto\x12\tsnowflake\"\x0f\n\rNextIdRequest\"\x1c\n\x0eNextIdResponse\x12\n\n\x02id\x18\x01 \x01(\t2Q\n\x10SnowflakeService\x12=\n\x06NextId\x12\x18.snowflake.NextIdRequest\x1a\x19.snowflake.NextIdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snowflake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEXTIDREQUEST']._serialized_start=30
  _globals['_NEXTIDREQUEST']._serialized_end=45
  _globals['_NEXTIDRESPONSE']._serialized_start=47
  _globals['_NEXTIDRESPONSE']._serialized_end=75
  _globals['_SNOWFLAKESERVICE']._serialized_start=77
  _globals['_SNOWFLAKESERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
