"""
Client for the Rust Snowflake ID service (ADR 0011).

`next_id()` is the single entry point the rest of the backend should use once
the service is wired in. Behaviour:

* `config.ID_SERVICE_ADDR` empty  -> mint locally via `utils.snowflake.next_id`
  (current behaviour, unchanged).
* `config.ID_SERVICE_ADDR` set    -> one **unary** `NextId` RPC per id. Never
  batched: the id's 41-bit timestamp is the routing key Postgres uses to pick a
  `messages` / `message_receipt_log` partition, so a buffered id would land in
  the wrong partition window.
* RPC error / timeout            -> fall back to the local generator for that
  call and log once, so id minting never hard-stops. A local-fallback id is
  still globally unique as long as `SNOWFLAKE_MACHINE_ID` differs from every
  Rust replica's `NODE_ID`.

The gRPC channel is created lazily on first use and reused (grpc.aio channels
are safe to share across coroutines).

Nothing imports this module yet - call sites are swapped in a follow-up.
"""
from __future__ import annotations

import logging

import config
from infra.ids.snowflake import next_id as _local_next_id

logger = logging.getLogger(__name__)

_channel = None  # grpc.aio.Channel | None
_stub = None
_warned_fallback = False


def _ensure_stub():
    global _channel, _stub
    if _stub is not None:
        return _stub
    import grpc  # noqa: PLC0415 - optional dep, only needed when the service is on
    from infra.ids._generated import snowflake_pb2_grpc  # generated by scripts/gen_proto.sh

    _channel = grpc.aio.insecure_channel(config.ID_SERVICE_ADDR)
    _stub = snowflake_pb2_grpc.SnowflakeServiceStub(_channel)
    return _stub


async def next_id() -> int:
    """Return a fresh Snowflake id as an int (mirrors utils.snowflake.next_id)."""
    if not config.ID_SERVICE_ADDR:
        return _local_next_id()

    global _warned_fallback
    try:
        from infra.ids._generated import snowflake_pb2  # generated

        stub = _ensure_stub()
        resp = await stub.NextId(
            snowflake_pb2.NextIdRequest(),
            timeout=config.ID_SERVICE_TIMEOUT_SECONDS,
        )
        return int(resp.id)
    except Exception as exc:  # noqa: BLE001 - any failure -> local fallback
        if not _warned_fallback:
            logger.warning(
                "id_service call failed (%s: %s); falling back to local generator",
                type(exc).__name__,
                exc,
            )
            _warned_fallback = True
        return _local_next_id()


async def close() -> None:
    """Close the gRPC channel (call from the app lifespan shutdown)."""
    global _channel, _stub
    if _channel is not None:
        await _channel.close()
        _channel = None
        _stub = None
